version: "3.8"
services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    volumes:
      - /mnt/user/appdata/collage-api/uploads:/app/uploads
      - /mnt/user/appdata/collage-api/outputs:/app/outputs
      - /mnt/user/appdata/collage-api/temp:/app/temp
    depends_on: [redis]
    restart: unless-stopped

  worker:
    build: .
    command: celery -A celery_app.celery_app worker -l info
    env_file: .env
    volumes:
      - /mnt/user/appdata/collage-api/uploads:/app/uploads
      - /mnt/user/appdata/collage-api/outputs:/app/outputs
      - /mnt/user/appdata/collage-api/temp:/app/temp
    depends_on: [redis]
    restart: unless-stopped

  redis:
    image: redis:7
    ports: ["6379:6379"]
    restart: unless-stopped
